doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            ulid_value: App\Users\Infrastructure\Database\Doctrine\Types\UlidValueType
            email_value: App\Users\Infrastructure\Database\Doctrine\Types\EmailValueType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Users:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/packages/doctrine/mapping/users'
                prefix: 'App\Users\Domain\Entity'
                alias: Users

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
