doctrine_migrations:
    migrations_paths:
#        'App\Shared\Infrastructure\Database\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Database/Migrations'
        'App\Users\Infrastructure\Database\Migrations': '%kernel.project_dir%/src/Users/Infrastructure/Database/Migrations'
    enable_profiler: '%kernel.debug%'
