security:
    password_hashers:
        App\Users\Infrastructure\Security\AuthUser:
            id: 'App\Users\Infrastructure\Service\UserPasswordHasher'

    providers:
        app_user_provider:
            id: 'App\Users\Infrastructure\Security\AuthUserProvider'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            pattern: ^/
            provider: app_user_provider
            custom_authenticators:
                - 'App\Users\Infrastructure\Security\LoginFormAuthenticator'
#            form_login:
#                login_path: /login
#                check_path: /login
#                default_target_path: /account
#            entry_point: form_login
            logout:
                path: /logout
                target: /

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER