App\Users\Domain\Entity\UserPasswordHistory:
    type: entity
    table: users_password_history
    id:
        id:
            type: ulid_value
            length: 26
            generator:
                strategy: NONE
    fields:
        password:
            type: string
            length: 255
        createdAt:
            type: datetime
    uniqueConstraints:
        unique_user_password:
            columns: [ user_id, password ]
    manyToOne:
        user:
            targetEntity: App\Users\Domain\Entity\User
            inversedBy: passwordHistory
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onUpate: CASCADE
                onDelete: CASCADE