parameters:
    users_import_directory: '%kernel.project_dir%/storage/import'
    mailer_sender: '%env(MAILER_SENDER)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Shared\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Shared\Application\Event\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    App\*\Domain\Factory\:
        namespace: App\
        public: true
        resource: '../src/*/Domain/Factory'
        exclude: '../src/Shared/*'