version: "3"

services:
    db:
        image: mysql:8.0.33
        container_name: db.dev
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app_dev:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app_dev

    php:
        container_name: php.dev
        build:
            context: ./php/dev
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_dev_var:/var/www/symfony/var
            - symfony_app_dev_vendor:/var/www/symfony/vendor
        ports:
            - 9000:9000
            - 9001:9001
        networks:
            - symfony_app_dev
        depends_on:
            - db
            - rabbitmq
            - mailer
        environment:
            APP_ENV: dev

    nginx:
        container_name: nginx.dev
        build:
            dockerfile: ./Dockerfile
            context: ./nginx/dev
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_dev_var:/var/www/symfony/var
            - symfony_app_dev_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - symfony_app_dev
        depends_on:
            - php

    rabbitmq:
        image: rabbitmq:3.12-management
        container_name: rabbitmq.dev
        restart: unless-stopped
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - symfony_app_dev
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit_user
            - RABBITMQ_DEFAULT_PASS=rabbit_pass

    mailer:
        image: schickling/mailcatcher
        container_name: mailer.dev
        restart: unless-stopped
        ports:
            - 1025:1025
            - 1080:1080
        networks:
            - symfony_app_dev

volumes:
    symfony_app_dev_var:
    symfony_app_dev_vendor:
    db_app_dev:

networks:
    symfony_app_dev:
