version: "3"

services:
    db:
        image: mysql:8.0.33
        container_name: db.test
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app_test

    php:
        container_name: php.test
        build:
            context: ./php/test
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony
        ports:
            - 9000:9000
            - 9001:9001
        networks:
            - symfony_app_test
        depends_on:
            - db
            - rabbitmq
            - mailer
        environment:
            APP_ENV: test

    nginx:
        container_name: nginx.test
        build:
            dockerfile: ./Dockerfile
            context: ./nginx/test
        volumes:
            - ../:/var/www/symfony:cached
        ports:
            - 80:80
        networks:
            - symfony_app_test
        depends_on:
            - php

    rabbitmq:
        image: rabbitmq:3.12-management
        container_name: rabbitmq.test
        restart: unless-stopped
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - symfony_app_test
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit_user
            - RABBITMQ_DEFAULT_PASS=rabbit_pass

    mailer:
        image: schickling/mailcatcher
        container_name: mailer.test
        restart: unless-stopped
        ports: [ 1025, 1080 ]
        networks:
            - symfony_app_test

networks:
    symfony_app_test:
